// console.log("hello1");
// alert("hello1");
// alert("hello2");
// console.log("hello2");

let value1 = " " + 1 + 0;
console.log(value1);
let value2 = " " - 1 + 0;
console.log(value2);
let value3 = 6 / "3";
console.log(value3);
let value4 = "2" * "3";
console.log(value4);
let value5 = "$" + 4 + 5;
console.log(value5);
let value6 = "4" - 2;
console.log(value6);
let value7 = -5 / 0;
console.log(value7);
let value8 = "-9" + 5;
console.log(value8);
let value9 = null + 1;
console.log(value9);
let value10 = 9 % 3;
console.log(value10);
let value11 = 9 % 23;
console.log(value11);
let value12 = 2 ** 16;
console.log(value12);
let value13 = 81 ** (1 / 2);
console.log(value13);
let a = b++;
console.log(a);
let c = ++d;
console.log(c);
let x = c + b++;
console.log(x);
